source 'https://rubygems.org'
gem 'capybara', '~>2.3.0'
gem 'rspec', '~>3.0.0'
gem 'selenium-webdriver', '~> 2.42.0'
gem 'poltergeist', '~> 1.5.1'
gem 'json', '~> 1.8.1'
gem 'pry', '~> 0.9.12.6'
gem 'rest-client', '~> 1.6.7'
gem 'cpf_faker', '~> 1.3.0'
gem 'rye', '~> 0.9.12'
gem 'capybara-screenshot', '~> 0.3.21'
gem 'capybara-webkit'
gem 'headless'